#!/bin/bash --

# Author: UnluckyTech

# Information:
# This script will install Arch Linux in UEFI. This script in specific was meant for personal use but feel free to edit and use as you please.

echo ""
echo "%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%"
echo "%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%"
echo "%%%%%                                                                    %%%%%"
echo "%%%%% This script will now begin the Installation of Arch Linux.         %%%%%"
echo "%%%%%                                                                    %%%%%"
echo "%%%%% If you are not running in EFI then stop and look over the script.  %%%%%"
echo "%%%%%                                                                    %%%%%"
echo "%%%%% Please take careful note of the console output.                    %%%%%"
echo "%%%%%                                                                    %%%%%" 
echo "%%%%% If you experience any issues with this script, please report them. %%%%%"
echo "%%%%%                                                                    %%%%%"
echo "%%%%% Look over the README.md to know what to input when needed.         %%%%%"
echo "%%%%%                                                                    %%%%%"
echo "%%%%% Script will begin in 10 seconds.                                   %%%%%"
echo "%%%%%                                                                    %%%%%"
echo "%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%"
echo "%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%"
echo ""

sleep 10

echo ""
echo "%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%"
echo "%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%"
echo "%%%%%                                        %%%%%"
echo "%%%%%    Preparing drive for Installation    %%%%%"
echo "%%%%%                                        %%%%%"
echo "%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%"
echo "%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%"
echo ""

sleep 2

gdisk /dev/sda
cgdisk /dev/sda
mkfs.fat -F32 /dev/sda1
mkswap /dev/sda2
swapon /dev/sda2
mkfs.ext4 /dev/sda3

echo ""
echo "%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%"
echo "%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%"
echo "%%%%%                                        %%%%%"
echo "%%%%%         Installing Arch Linux          %%%%%"
echo "%%%%%                                        %%%%%"
echo "%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%"
echo "%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%"
echo ""

sleep 2

mount /dev/sda3 /mnt
mkdir /mnt/boot/
mkdir /mnt/home
mount /dev/sda1 /mnt/boot
pacstrap -i /mnt base base-devel
genfstab -U -p /mnt >> /mnt/etc/fstab

echo ""
echo "%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%"
echo "%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%"
echo "%%%%%                                        %%%%%"
echo "%%%%%     Arch Linux is now Installed        %%%%%"
echo "%%%%%                                        %%%%%"
echo "%%%%%                                        %%%%%"
echo "%%%%%     Will now chroot into the OS        %%%%%"
echo "%%%%%                                        %%%%%"
echo "%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%"
echo "%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%"
echo ""

sleep 5

arch-chroot /mnt
